import Link from "next/link"
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }) {
 return (
    <html lang="en"> 
      <body>
        <header>
          <p className="bg-slate-500">Header</p>
          <Link href={'/'}>Home</Link>
          <Link href={'/about'}>About</Link>
          <Link href={'/product'}>Products</Link>
          <Link href={'/profile'}>Profile</Link>
        </header>
        {children}
        <footer>
          <p className="bg-gray-500">Footer</p>
        </footer>
      </body>
    </html>
  )
}
