'use client'
import Link from "next/link"
import { usePathname } from "next/navigation"
import { useState } from "react"
import "../index.css"
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }) {

  const [input, setInput] = useState("");

    const navLink = [
        {name: 'Register', href: '/register'},
        {name: 'Login', href: '/login'},
        {name: 'Forgot Password', href: '/forgot-password'}
    ]

    const pathName = usePathname()

 return (
    <html lang="en">
      <body>

        <input
          type="text"
          id="id"
          name="name"
          value={input}
          onChange={(e)=>setInput(e.target.value)}
          placeholder="placeholder"
          className="w-[300px] border text-black border-slate-200 rounded-lg py-3 px-5 outline-none	bg-transparent"
        />

        {
            navLink.map((link) => {
                const isActive = pathName.startsWith(link.href);
                return (
                    <Link href={link.href} className={isActive ? 'font-bold mr-4' : 'text-blue-500 mr-4'}>{link.name}</Link>
                )
            })
        }
        {children}
      </body>
    </html>
  )
}
